### ISSUE TITLE
Execution exception

### ISSUE THREAD

**Issue by LOverride** [guardian/frontend#11448]
When I try to run the project, this appear when I use http://localhost:9000/news/gallery/2012/dec/04/24-hours-in-pictures-gallery

And this log appear in the terminal:

[ERROR] [01/05/2016 09:29:03.657] [application-akka.actor.default-dispatcher-22] [ActorSystem(application)] Uncaught fatal error from thread [application-akka.actor.default-dispatcher-22] shutting down ActorSystem [application]
java.lang.NoClassDefFoundError: Could not initialize class conf.LiveContentApi$
	at controllers.ArticleController$.lookup(ArticleController.scala:138)
	at controllers.ArticleController$.mapModel(ArticleController.scala:128)
	at controllers.ArticleController$.controllers$ArticleController$$loadArticle(ArticleController.scala:118)
	at controllers.ArticleController$$anonfun$renderArticle$2.apply(ArticleController.scala:113)
	at controllers.ArticleController$$anonfun$renderArticle$2.apply(ArticleController.scala:112)
	at performance.MemcachedAction$$anonfun$apply$2$$anonfun$apply$4.apply(MemcachedAction.scala:131)
	at performance.MemcachedAction$$anonfun$apply$2$$anonfun$apply$4.apply(MemcachedAction.scala:125)
	at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:251)
	at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:249)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
	at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply$mcV$sp(BatchingExecutor.scala:91)
	at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply(BatchingExecutor.scala:91)
	at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply(BatchingExecutor.scala:91)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:72)
	at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:90)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:40)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:397)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

---------------------------- WARNING ------------------------------------
URL /uk/media has NO CACHE-CONTROL header
-------------------------------------------------------------------------------

**Comment by rich-nguyen** [comment]
Hi @LOverride, thanks for your interest in our repo. The error you are encountering here is due to a required `frontend.properties` file. This issue is similar to #9923, we don't provide a default set of properties, since many of these properties are private values. As mentioned in issue #9923
, aside from the readme, we aren't able to provide external developer support for running the project locally.
