### ISSUE TITLE
"Too many operations in progress" in `FrontJsonFapi` fetching

### ISSUE THREAD

**Issue by rtyley** [guardian/frontend#26335]
There have been several recent incidents where the serving of fronts (eg https://www.theguardian.com/uk) to users became slow, and in fact failed.

There's a lot of things going on in these incidents, but in particular we do see these `TooManyOperationsInProgress ` errors in the [logs](https://logs.gutools.co.uk/s/dotcom/goto/5b477880-2586-11ee-a9e1-e75870600741):

```
Failed rendering world with concurrent.FutureSemaphore$TooManyOperationsInProgress: Too many operations in progress, 
cannot execute task
concurrent.FutureSemaphore$TooManyOperationsInProgress: Too many operations in progress, cannot execute task
	at concurrent.FutureSemaphore.execute(FutureSemaphore.scala:16)
	at services.fronts.FrontJsonFapi.parsePressedPage(FrontJsonFapi.scala:34)
	at services.fronts.FrontJsonFapi.$anonfun$pressedPageFromS3$2(FrontJsonFapi.scala:58)
```

![image](https://github.com/guardian/frontend/assets/52038/e7e3a64b-1281-4cfb-b493-7fbd01a6a595)

- https://github.com/guardian/frontend/pull/18331 - 27th November 2017 : introduced `futureSemaphore`, limiting the number of concurrent operations to 10 per server
- https://github.com/guardian/frontend/pull/18359 - 30th November 2017 : introduced the use of `blockingOperations.executeBlocking` to `FrontJsonFapi` - non-async, thread-blocking code

**Comment by rtyley** [comment]
We've had 2 `TooManyOperationsInProgress` outages recently ([ELK logs](https://logs.gutools.co.uk/s/dotcom/goto/a618b590-2c7f-11ee-a2fd-a753b3d7df93)):

* 13th July : [`12:35 - 12:55`](https://logs.gutools.co.uk/s/dotcom/goto/467060b0-2c80-11ee-9622-01aeb9449a91) (20 minutes) - 49662 errors (peaking at 5133 requests per minute) over just [356 paths](https://docs.google.com/spreadsheets/d/1sJ4rPG713DaW0ksub-OjrYXszX7gwyJT_u4i2PFlniw/edit#gid=1078329898) <img width="1727" alt="image" src="https://github.com/guardian/frontend/assets/52038/571b9428-3a6d-4563-ae27-4f85be65ab96"> Initially there were [3 facia app-servers running](https://logs.gutools.co.uk/s/dotcom/goto/196eac20-2c85-11ee-a2fd-a753b3d7df93) (this was immediately after a deploy, facia scaled up to 12 across the course of the outage) ![image](https://github.com/guardian/frontend/assets/52038/a67fb6d9-db2a-4e25-b088-9033b24a549e)

* 19th July : [`9:35 - 9:57`](https://logs.gutools.co.uk/s/dotcom/goto/8e16d0c0-2c80-11ee-8f66-4b36648d933b) (22 minutes) - 58577 errors (peaking at 4618 requests per minute) <img width="1727" alt="image" src="https://github.com/guardian/frontend/assets/52038/ba105b4f-dd96-4d45-83bd-0bf53f566a6a">

I've exported the [data](https://docs.google.com/spreadsheets/d/1sJ4rPG713DaW0ksub-OjrYXszX7gwyJT_u4i2PFlniw/edit?usp=sharing) for these outages out of the ELK, just trying to understand what paths are being requested

The rate of 5133 errors per minute is really high, given that fronts have a CDN cache time of 1 minute, and that only 356 different paths were being requested (or at least erroring) in the outage - the number of requests is 5133/356 = 14 times what an optimal request rate would be. In other words, if requests had been succeeding, and getting cached, there would have been 14x less traffic - but they were failing, being throttled by `futureSemaphore`.

**Comment by rtyley** [comment]
I described a possible failure mode for Facia here: https://github.com/guardian/frontend/pull/26336#issuecomment-1645645161 - basically, `futureSemaphore` would throw away 'download' work already done (ie downloading entire S3 files to `String`s in memory) because of it's max-32-concurrent-actions limit on decoding, rather than holding on to that work and completing it so that a successful result could be returned to the CDN and cached - lack of CDN caching meant that many requests were repeated, and this would probably have led to increased GC pressure.

This [graph](https://eu-west-1.console.aws.amazon.com/cloudwatch/home?region=eu-west-1#metricsV2?graph=~(metrics~(~(~'Application~'front-download-latency~'ApplicationName~'facia~'Stage~'PROD~(color~'*2398df8a~visible~false))~(~'...~(yAxis~'right~color~'*232ca02c~stat~'SampleCount))~(~'.~'front-decoding-latency~'.~'.~'.~'.~(color~'*23c5b0d5~visible~false))~(~'...~(yAxis~'right~color~'*239467bd~stat~'SampleCount))~(~'.~'G1_Young_Generation-gc-time-per-min~'.~'.~'.~'.~(color~'*23d62728~visible~false)))~view~'timeSeries~stacked~false~region~'eu-west-1~stat~'Average~period~60~start~'2023-07-19T08*3a30*3a00.532Z~end~'2023-07-19T09*3a05*3a00.919Z)&query=~'*7bApplication*2cApplicationName*2cStage*7d*20G1) shows how many `download`s vs how many `decode`s Facia was doing. When the server was healthy, these were the same number - when things go wrong, you can see **we are doing many more downloads than decodes** - all that extra download work is achieving is generating more garbage collection & consuming threads from the `blockingOperations` thread pool.

![image](https://github.com/guardian/frontend/assets/52038/30d3f60b-989d-4256-9d3d-7ed6e1e290ef)
